### ISSUE TITLE
Why pub/sub when we already have jQuery.bind/triggerHandler?

### ISSUE THREAD

**Issue by timmolendijk** [mikehostetler/amplify#1]
Ever since jQuery officially supports wrapping non-DOM-elements, it essentially contains a generic pub/sub system:

```
$(anyobject).bind("dataexample", function(e, data) { alert(data.foo); });
...
$(anyobject).triggerHandler("dataexample", { foo: "bar" });
```

So why not just use that instead of the custom pub/sub implementation in `core`?

**Comment by scottgonzalez** [comment]
This is not an issue and was already posted on Google Groups.

**Comment by timmolendijk** [comment]
True. Wasn't sure how you are intending to use this issue tracker. Groups tend to be easily neglected. Will continue this discussion in Groups.
