### ISSUE TITLE
The error setting is ignored by amplify.request.define

### ISSUE THREAD

**Issue by instanceofme** [mikehostetler/amplify#22]
```
amplify.request.define('custom', 'ajax', {
    url: '/nowhere',
    error: function(){ alert('error'); }
});
// ...
amplify.request({ resourceId: 'custom' });
```

The alert never shows. But if I move the `error` param to the `amplify.request()` call, it works.
See [this fiddle](http://jsfiddle.net/U3fHd/) (uses HEAD scripts on this github).

**Comment by scottgonzalez** [comment]
That's an invalid use of the API. You shouldn't be defining an error callback in your definition. Error handling is up to the person making the request, not the person defining the request. If you need to treat errors in a certain way, use a decoder.

**Comment by instanceofme** [comment]
[Same with success](http://jsfiddle.net/LNEag/). I guess this is by design… Why not give the possibility?

**Comment by scottgonzalez** [comment]
Because we want complete separation between the definition of a request and the handling of a request. If you're actually handling an error, it doesn't belong in the definition.
