### ISSUE TITLE
Improve docs on custom cache

### ISSUE THREAD

**Issue by strathmeyer** [mikehostetler/amplify#36]
http://amplifyjs.com/api/request/#custom_cache

Needs:
- information on what the custom cache function should return (scott says, "quick answer: don't return anything if you don't have the value cached.  if you do have the value cached, invoke the ajaxSettings.success callback with the value and return false")
- maybe an example?

**Comment by jakerella** [comment]
Link to the doc section changed: http://amplifyjs.com/api/request/#customcache
