### ISSUE TITLE
sessionStorage method absent in IE9 on server 2008 r2

### ISSUE THREAD

**Issue by ronnyle** [mikehostetler/amplify#45]
On server 2008 r2 running chrome/firefox sessionStorage functions fine, however IE9 on the same machine will throw:
Object doesn't support property or method 'sessionStorage'

**Comment by scottgonzalez** [comment]
Can you provide more details? Does this error occur on load or when you try to use sessionStorage? If it occurs when you try to use sessionStorage, does amplify claim to support sessionStorage in that browser?

**Comment by ronnyle** [comment]
The error occur when I try to use the sessionStorage. Regular storage works fine.
Internet Explorer 9 is claimed to be supported by AmplifyJS, and it is working on other machines, just not server 2008 r2.
Thanks

**Comment by scottgonzalez** [comment]
Does `window.sessionStorage` work? Just because a browser is supported, doesn't mean that the environment or user hasn't disabled certain features.

**Comment by ronnyle** [comment]
you're right, it's disabled in my environment. I guess I expected some fallback. Thank you.
