### ISSUE TITLE
IE9 issue - amplify is undefined

### ISSUE THREAD

**Issue by sumityadav** [mikehostetler/amplify#54]
I was on page: http://amplifyjs.com/api/store/ and tried to run the fiddler sample and i get the following error message(s).

Screenshot: http://screencast.com/t/qRK5dkk28Lo

Console output:

SEC7112: Script from https://raw.github.com/appendto/amplify/master/core/amplify.core.js was blocked due to mime type mismatch 
light
SEC7112: Script from https://raw.github.com/appendto/amplify/master/store/amplify.store.js was blocked due to mime type mismatch 
light
SCRIPT5009: 'amplify' is undefined 
light, line 34 character 5

**Comment by scottgonzalez** [comment]
I think we just need to leave this. We're not providing a CDN, so there's no other resource to link to.
