### ISSUE TITLE
Store fails when newer IEs run in IE 7 mode

### ISSUE THREAD

**Issue by scottgonzalez** [mikehostetler/amplify#6]
If you set IE 9 to run in IE 7 mode, then IE claims to support localStorage, but will fail when trying to delete data.

**Comment by joemaffia** [comment]
What happen to me is quite a weird issue, IE6 and IE7 throw a message error when the page load (only if amplify is between my loaded plugins):

Unable to open the Internet site... Operation Aborted

**Comment by scottgonzalez** [comment]
joemaffia: That sounds like a completely different issue since IE 9 doesn't have an IE 6 mode. Please open a new bug with a reduced test case. Also, make sure you're testing against master and not the alpha.
