### ISSUE TITLE
Throw an exception when data returned to does not conform to jsend

### ISSUE THREAD

**Issue by brianmhunt** [mikehostetler/amplify#60]
When I make an amplify.js `request`, and the response does not conform to the jsend spec, it would be nice if amplify.js threw an exception (or could be run in "strict" mode where it would throw an exception).

This would help a little bit with debugging, since at the moment it seems that when an amplify.js `request` does not conform to the jsend spec neither the success nor error handler are called - the response is silently ignored. Explicit failure is preferable.

Thanks!

**Comment by scottgonzalez** [comment]
I'd much rather invoke the error callback than throw an error.

**Comment by brianmhunt** [comment]
@scottgonzalez I completely agree.

I am not sure how client-side errors fit into the [jsend spec](http://labs.omniti.com/labs/jsend). I presume an error can simply be generated on the client side.
