### ISSUE TITLE
amplify.store('key') always return null when navigate Back from another page

### ISSUE THREAD

**Issue by cheeaun** [mikehostetler/amplify#61]
Here's a testcase: http://jsbin.com/3/oxexoc

On initial page load, everything works fine until you click on a web page (on another domain) then navigate Back. The `localStorage` reference in amplify.store code seems lost and returns a zero `length`, which probably explains why amplify.store('key') is always returning `null`. If you try to access directly to the `localStorage` instance, the key is actually there.

This bug is replicable on Safari 5.1.2 (7534.52.7) on Windows and Mobile Safari (7534.48.3) on iOS5 (iPhone).

**Comment by jakerella** [comment]
Just confirming, the demo is working on Chrome & Firefox on Linux, and Chrome, IE 8, **and Safari** on Windows XP. IE9 blocks the script include from raw Github files, but my guess is it works there just fine.

**Comment by jakerella** [comment]
Fixed the jsbin for IE9 (which requires proper mime types on script includes): http://jsbin.com/oboleh/1/

**Comment by dcneiner** [comment]
Also tested this on Safari 6 on Mac, and Safari on iOS 6, couldn't duplicate. It has either been fixed, or we'll need more information to duplicate it. Closing for now. Thanks for checking @jakerella
