### ISSUE TITLE
Does it support cross-domain requests with authentication?

### ISSUE THREAD

**Issue by balupton** [mikehostetler/amplify#64]
In the request documentation, there is `Any settings found in jQuery.ajax().`

However, doesn't appear to support xhrFields which is needed for cross domain authentication, [see here](http://api.jquery.com/jQuery.ajax/)

Does amplify request support cross-domain requests with authentication?

**Comment by scottgonzalez** [comment]
It's almost a direct pass-thru to `$.ajax()` so I don't see why this wouldn't work. See https://github.com/appendto/amplify/blob/master/request/amplify.request.js#L122 and https://github.com/appendto/amplify/blob/master/request/amplify.request.js#L202

Do you have an example of this working with `$.ajax()` but not with `amplify.request()`?

**Comment by scottgonzalez** [comment]
ping @balupton

**Comment by balupton** [comment]
Ah okay, that's good by me :) Haven't had a chance to give it a go yet so can't confirm yet.
