### ISSUE TITLE
Store fails to load in IE6 and IE7

### ISSUE THREAD

**Issue by joemaffia** [mikehostetler/amplify#7]
I've been checking also the /amplify/src/store/test/test.html unit-test and it won't load the page at all under IE6 or 7

**Comment by scottgonzalez** [comment]
it works fine for me: http://swarm.amplifyjs.com/?state=runresults&run_id=293&client_id=2287

**Comment by joemaffia** [comment]
mhh that's strange... in my test the other libraries were jQuery 1.5.2 and jQuery UI 1.8.9

but then it's more weird that the test.html dowloaded on the site doesn' work. I'll try with your link

**Comment by joemaffia** [comment]
This is enough on my case to stop loading the page...
if I took off the amplify library then all is fine.

``` html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <title>amplify test</title> 
</head>
<body>
    <script src="_scripts/jquery-1.5.2.min.js"></script>
    <script src="_scripts/amplify.min.js"></script>
</body>
</html>
```

**Comment by scottgonzalez** [comment]
Is that the alpha since it's minified?

**Comment by joemaffia** [comment]
yes, it's the one you can download from the site directly...

**Comment by scottgonzalez** [comment]
Please test against master. There's a known bug in the alpha that was fixed a while ago.

**Comment by joemaffia** [comment]
indeed it works :)

Are u going to include the json2 in the minified version of the amplify.core?

**Comment by scottgonzalez** [comment]
No, we won't package any dependencies in our minified files.
