### ISSUE TITLE
Not enough Storage with HTML Payload and cache:persist

### ISSUE THREAD

**Issue by mettlus** [mikehostetler/amplify#74]
I am using html payload instead of JSON (since I am returning Partial View from my ASP.NET MVC Project) Every now and then I run into error from amplify which states that there is not enough storage when cache:persist is used
How can I go past this error? TIA

**Comment by scottgonzalez** [comment]
This is not a bug. Persistent caches have browser-defined limits. How you handle the limits is up to you.
