### ISSUE TITLE
Demos need to include json2.js

### ISSUE THREAD

**Issue by adofito** [mikehostetler/amplify#8]
I am running IE 7.0.5730.13 running in a VMware image that Microsoft makes available for testing purposes and it fails everytime.

You can download the images at: 
http://www.microsoft.com/downloads/en/details.aspx?FamilyId=21EABB90-958F-4B64-B5F1-73D0A413C8EF&displaylang=en

(they are VPC image files but it is possible to make them into VMWare Images)

I am using this link to test in fiddle:
http://jsfiddle.net/gh/get/jquery/1.5/appendto/amplify/tree/master/store/demo/implicit/

I get this javascript error:
Line:204
Char:6
Error: 'JSON' is undefined

thanks,

Carlos

**Comment by scottgonzalez** [comment]
You have to include json2.js in browsers that don't have native JSON support.

**Comment by adofito** [comment]
Thanks, it seems to be working now. Maybe it would be a good idea to include this in the documentation. It is not clear anywhere. It just estates that it works with IE5+ and no dependencies listed either.

Thanks,

Carlos
