### ISSUE TITLE
Bug in unsubscribe with equal callbacks

### ISSUE THREAD

**Issue by redmagic** [mikehostetler/amplify#85]
Hi,

When 2 subscribers are listening to a topic and have the same callback function, but are registered with different contexts, the unsubscribe will fail. The first listener will be unsubscribed.

Example:

``` javascript
function A() {

    amplify.subscribe('myevent', this, this.doIt)
}
A.prototype = {
    doIt: function () {
        .....
    }
}
var x = new A(), y = new A();

amplify.unsubscribe('myevent', y, y.doIt); //Will fail
```

Fix:

Check for context equality on unsubscribing:

``` javascript
        for ( ; i < length; i++ ) {
            if ( subscriptions[ topic ][ i ].callback === callback && subscriptions[ topic ][ i ].context === context ) {
                subscriptions[ topic ].splice( i, 1 );
                break;
            }
        }
```

**Comment by dcneiner** [comment]
Hi @redmagic, I [worked on a new test](https://github.com/appendto/amplify/commit/396196fa9c21ea83fac46a4eddceb51474e19177) to try to duplicate your issue. It seems to unsubscribe correctly with the current functionality.

``` javascript
amplify.unsubscribe('myevent', y, y.doIt); //Will fail
```

That will certainly fail because you cannot pass in the context to the unsubscribe method currently. However, this works as expected:

``` javascript
amplify.unsubscribe( 'myevent', y.doIt )
```

**Comment by dcneiner** [comment]
@redmagic – Ah, nevermind, my test was not fully showing the problem. You are correct this is a bug.

**Comment by dcneiner** [comment]
@redmagic - Please download this version and see if it fixes your issues. Thanks for alerting us to the issue. I also adjusted the behavior for unsubscribe to unsubscribe _all_ matching functions (and matching context if provided) instead of just the first one.

**Comment by redmagic** [comment]
Hi Douglas,

Thanks for your quick response to this issue. I've tested the new build and it resolves the issue correctly.

Keep up the good work!
