### ISSUE TITLE
Amplify.js breaks jQuery type attribute selector in IE7

### ISSUE THREAD

**Issue by spudly** [mikehostetler/amplify#89]
If amplify.js is included on a page with jQuery, it causes the following jQuery selector to fail in IE7:

``` javascript
$('[type="something"]');
```

It throws this error: `Object doesn't support this property or method` with no file or line information to tell you where it came from.

This happens in a real version of IE7 only! It cannot be reproduced in ie7 browser mode or ie7 document mode. I had to download microsoft's ie7 virtual machine image in order to debug this.

This selector works just fine if amplify.js is not included on the page. When amplify is there, it fails.

Does not fail alongside jQuery 1.9.1. Fails in both 1.10.1 and 1.10.2.

amplify.js version is 1.1.0

See also:
http://bugs.jquery.com/ticket/14151 (original bug report on jquery bug tracker)
http://jsfiddle.net/BG5aT/12/ (to edit the fiddle)
http://jsfiddle.net/BG5aT/12/show/ (to view the error in IE7)

**Comment by scottgonzalez** [comment]
This is out of scope for amplify. Continue tracking in the jQuery bug report.
