### ISSUE TITLE
BUG:  amplify.request on IE 9 not work

### ISSUE THREAD

**Issue by bao1018** [mikehostetler/amplify#99]
I just define very simple ajax request and run on IE 9, no HTTP request was sent to the server when I run it. 

I run same code on other browser and it works. Please help to fix

**Comment by dcneiner** [comment]
@bao1018 Can you please show us your code?

**Comment by bao1018** [comment]
@dcneiner Maybe it is not a bug, I just find the server side is CORS enabled, looks like amplify doesn't work on IE 9 if the server side is CORS. I will close this out.
